config/routes.rb
Porker::Application.routes.draw do
  resources :plans do
    resources :cards do
      collection { get :events }
    end
  end
end

app/models/card.rb
class Card
  include Mongoid::Document
  include Mongoid::Timestamps

  field :point, type: Integer
  field :note, type: String
  belongs_to :plan
end

app/models/plan.rb
class Plan
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :current_plan
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = @plan.cards
    @card = Card.new
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    response.headers["Content-Type"] = "text/javascript"
    @card = @plan.cards.new(card_params)
    @card.save
    $redis.publish('messages.create', @card.to_json)
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to plan_path(@plan), notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to plan_path(@plan) }
      format.json { head :no_content }
    end
  end

=begin
  def events
    response.headers["Content-Type"] = "text/event-stream"
    3.times do |n|
      response.stream.write "data: #{n}...\n\n"
      sleep 2
    end

  end
=end

  def events
    response.headers["Content-Type"] = "text/event-stream"
    start = Time.zone.now
    5.times do |n|
      #@plan.cards.where(:created_at.gt => Time.zone.now).each do |card|
      str = {text: ""}
      @plan.cards.each do |card|
        str[:text] += "#{card.point}pt (#{card.note})\n"
        #response.stream.write "data: #{card.to_json}\n\n"
        #start = Time.zone.now
      end
      response.stream.write "data: #{str.to_json}\n\n"
      sleep 1
    end
  rescue IOError
    logger.info "Stream closed"
  ensure
    response.stream.close
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = @plan.cards.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:point, :note)
    end

    def current_plan
      @plan = params[:plan_id].blank? ? nil : Plan.find(params[:plan_id])
    end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card, url:plan_cards_path(@plan), remote: true) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :point %><br />
    <%= f.select :point, [0,1,2,3,5,8,13,20,40,100] %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/create.js.erb
$("#card_note").val('');

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1><%= @plan.title %></h1>

<%= render 'form' %>

<pre id="card">
<%= @plan.cards.map {|v| "#{v.point}pt (#{v.note})\n" }.join %>
</pre>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', plan_cards_path(@plan) %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num:</strong>
  <%= @card.num %>
</p>

<p>
  <strong>Note:</strong>
  <%= @card.note %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Porker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<%= link_to 'New Plan', new_plan_path, class:'btn' %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @plan.title %>
  </p>


<%= link_to 'Destroy', @plan, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn' %>
<%= link_to 'Edit', edit_plan_path(@plan), class:'btn' %>

<%= link_to 'New Point', plan_cards_path(@plan), class:'btn' %>